# Generated by Django 4.2.5 on 2023-09-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('producto', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('insumo_instalado', models.CharField(max_length=255)),
                ('so', models.CharField(max_length=255)),
                ('memoria', models.CharField(max_length=255)),
                ('procesador', models.CharField(max_length=255)),
                ('antivirus', models.CharField(max_length=255)),
                ('vence', models.DateTimeField()),
            ],
        ),
    ]
